[package]
name = "repodex"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.10.0"
lambda_runtime = "0.10.0"
rustemon = "3.4.0"
serde = "1.0.197"
serde_json = "1.0.114"
tokio = { version = "1.35.1", features = ["macros"] }
