[package]
name = "repodex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.9.1"
serde = "1.0.195"
serde_json = "1.0.111"
tokio = "1.35.1"
tracing = "0.1.27"
